version: '3.8'
services:
  # أداة عرض قواعد البيانات (الواجهة الرسومية)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_taxi
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8082:80"
    depends_on:
      - pgdatabase

  # قاعدة بيانات التاكسي (الهدف اللي هنخزن فيه الداتا)
  pgdatabase:
    image: postgres:13
    container_name: pg_taxi
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - taxi_db_data:/var/lib/postgresql/data

  # قاعدة بيانات Airflow (المطبخ الداخلي للأداة)
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # خدمة تهيئة قاعدة البيانات وإنشاء المستخدم لأول مرة
  airflow-init:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
    command: >
      bash -c "airflow db init &&
      airflow users create --username airflow --password airflow --firstname Admin --lastname Admin --role Admin --email admin@example.com"

  # واجهة مستخدم Airflow
  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: airflow_webserver
    restart: always
    command: webserver
    depends_on:
      - postgres
      - airflow-init
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

  # المحرك اللي بيشغل الـ DAGs في وقتها
  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow_scheduler
    restart: always
    command: scheduler
    depends_on:
      - postgres
      - airflow-init
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

volumes:
  postgres_data:
  taxi_db_data: